### PR TITLE
Contributors list fully automated

### LINKED ISSUE #25: Add Contributor's List in Readme.
There are many contributors to an open source project.
It is always a good idea to give our contributors a shout-out.  :tada: 

We would be happy to include a list of contributors who have been contributing to this project. :gift_heart: 
**The task is to add a list of contributors (in a clean, concise, and attractive way) to the Readme of the project.**

**Additional context**
A simple start can be considered, but
It will be a bonus if the whole process can be automated. :+1: :star:

### PR DESCRIPTION
**Pull request by aswin2108**
Fix #25
Code added to add contributor's name and to automate it.

### CODE REVIEW

**Comment by aswin2108** [comment]
@noviicee Can you please check it?

**Comment by aswin2108** [comment]
@noviicee I have squashed and rebased it! Can you pls check it!

**Review by noviicee — APPROVED** [review]
lgtm for now!

**Comment by noviicee** [comment]
@aswin2108 thank you for the help!
And congratulations on getting your first Pull Request merged in [Banque-De-Questions](https://github.com/noviicee/Banque-De-Questions)! :tada: 
Keep contributing. :rocket:

**Pull request merged**
